In [22]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Function to extract data from each page
def extract_data(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    table = soup.find('table')
    df = pd.read_html(str(table))[0]
    return df

# Base URL
base_url = "https://www.screener.in/screens/1635381/pe-increasing/?page="

# Loop through each page from page=1 to page=35 and extract data
dfs = []
for page_num in range(1, 137):
    url = base_url + str(page_num)
    df = extract_data(url)
    dfs.append(df)

# Concatenate all DataFrames into a single DataFrame
final_df1 = pd.concat(dfs, ignore_index=True)

# Display the DataFrame

In [23]:
# Filter out rows containing 'Name' in the 'Name' column
final_df_filter1 = final_df1[~final_df1['Name'].str.contains('Name')]

final_df_filtered1=final_df_filter1[~final_df_filter1['Name'].str.contains('Median')]

In [24]:
# Function to extract data from each page
def extract_data(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    table = soup.find('table')
    df = pd.read_html(str(table))[0]
    return df

# Base URL
base_url = "https://www.screener.in/screens/1635382/roic-decreasing/?page="

# Loop through each page from page=1 to page=35 and extract data
dfs = []
for page_num in range(1, 138):
    url = base_url + str(page_num)
    df = extract_data(url)
    dfs.append(df)

# Concatenate all DataFrames into a single DataFrame
final_df2 = pd.concat(dfs, ignore_index=True)

In [25]:
# Filter out rows containing 'Name' in the 'Name' column
final_df_filter2 = final_df2[~final_df2['Name'].str.contains('Name')]

final_df_filtered2=final_df_filter2[~final_df_filter2['Name'].str.contains('Median')]

In [26]:
excel_file_path = "data_extracted1.xlsx"

# Save the DataFrame to an Excel file
final_df_filtered1.to_excel(excel_file_path, index=False)

In [27]:
excel_file_path = "data_extracted2.xlsx"

# Save the DataFrame to an Excel file
final_df_filtered2.to_excel(excel_file_path, index=False)

In [28]:
df1=pd.read_excel('data_extracted1.xlsx')
df2=pd.read_excel('data_extracted2.xlsx')

In [29]:


# 1. Sort by "P/E"
df1 = df1.sort_values('P/E', ascending=True)

# 2. Reset index to create row numbers
df1 = df1.reset_index(drop=True)  # drop=True removes the old index

# 3. Add 1 to get conventional row numbering starting from 1
df1['Row Number 1'] = df1.index + 1


df1.head(15)

,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %,Row Number 1
0,1.0,Reliance Home,3.65,0.03,177.05,0.00,-2.56,98.97,0.16,-99.89,257.70,1
1,2.0,Sobhagya Mercant,21.44,0.07,0.87,0.00,2.16,-27.27,27.43,-14.17,43.94,2
2,3.0,Siddha Ventures,9.14,0.45,9.14,0.00,-0.02,-122.22,0.00,-100.00,72.58,3
3,4.0,Autoriders Intl.,75.79,0.46,3.71,0.66,3.20,46.12,21.29,24.28,27.38,4
4,5.0,Satchmo Holdings,3.26,0.65,47.54,0.00,-25.70,-3094.12,6.20,-67.79,NaN,5
5,6.0,Press. Senstive,7.80,0.77,115.72,0.00,40.47,202450.00,95.73,NaN,109.67,6
6,7.0,Steel Strips Inf,36.00,0.82,31.10,0.00,-6.66,-4262.50,0.31,10.71,NaN,7
7,8.0,Hind.Natl.Glass,20.65,0.86,184.93,0.00,44.58,683.51,617.43,4.75,-15.10,8
8,9.0,Sr. Jayala. Auto,6.18,0.86,2.77,0.00,3.45,NaN,0.00,NaN,-8.70,9
9,10.0,Kavveri Telecom,14.35,0.91,29.13,0.00,-0.30,-3.45,0.74,-25.25,24.97,10
10,11.0,Key Corp,118.95,1.02,71.37,0.00,29.82,68.38,30.08,68.23,32.08,11
11,12.0,Mukta Agricultur,3.72,1.06,8.07,0.00,-0.01,0.00,0.00,NaN,27.29,12
12,13.0,Adarsh Mercantil,8.85,1.20,3.25,0.00,0.40,1233.33,0.00,NaN,0.09,13
13,14.0,Mercury Trade Li,5.48,1.23,1.49,0.00,0.39,4000.00,4.01,NaN,0.00,14
14,15.0,Sadbhav Infra.,6.80,1.32,241.00,0.00,-122.82,40.04,203.60,10.31,12.28,15

In [30]:
# 1. Sort by "ROIC"

df2['Row Number 2'] = df2.reset_index(drop=True).index + 1

df2.head(15)

,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %,ROIC %,Row Number 2
0,1.0,Reliance Home,3.65,0.03,177.05,0.00,-2.56,98.97,0.16,-99.89,257.70,42584.85,1
1,2.0,Cons. Finvest,255.90,2.48,828.20,0.00,9.87,-0.10,14.41,316.47,65.96,18409.13,2
2,3.0,Harshdeep,70.72,17.38,113.82,0.00,3.60,NaN,25.27,NaN,18600.00,13971.33,3
3,4.0,Pilani Invest.,3822.45,20.15,4234.11,0.39,55.52,54.01,61.66,17.54,2.26,12408.84,4
4,5.0,Indl.& Prud.Inv.,5358.85,17.67,898.06,1.12,11.94,18.92,1.64,-42.25,7.37,7710.34,5
5,6.0,Key Corp,118.95,1.02,71.37,0.00,29.82,68.38,30.08,68.23,32.08,7314.29,6
6,7.0,HDFC AMC,3660.40,40.16,78143.68,1.31,541.09,43.83,695.43,28.56,37.72,3632.17,7
7,8.0,Medinova Diagno.,35.89,16.59,35.83,0.00,0.40,73.91,2.39,7.66,2684.21,2684.21,8
8,9.0,Ashika Credit,75.18,5.31,89.31,0.00,9.74,467.55,13.68,640.71,13.59,2295.72,9
9,10.0,Saraswati Commer,5335.00,8.57,549.46,0.00,33.32,296.67,40.08,227.45,4.60,2234.51,10
10,11.0,JSW Holdings,6846.35,46.40,7597.74,0.00,34.71,15.93,27.29,4.88,2.04,1848.37,11
11,12.0,Kavveri Telecom,14.35,0.91,29.13,0.00,-0.30,-3.45,0.74,-25.25,24.97,1772.24,12
12,13.0,NBI Indl. Fin.,1857.30,65.28,456.30,0.02,0.34,1033.33,0.97,61.67,0.35,1550.00,13
13,14.0,Rita Finance and,20.22,30.64,20.22,0.00,0.17,-15.00,0.28,-12.50,5.43,1500.00,14
14,15.0,Morarka Finance,151.20,12.69,68.04,3.31,0.37,76.19,0.75,66.67,2.39,1421.21,15

In [38]:
# Merge DataFrames on the 'Name' column
merged_df = df1.merge(df2, on='Name', how='inner')

# Calculate combined row numbers directly
merged_df['Combined Row Number'] = merged_df['Row Number 1'] + merged_df['Row Number 2']

In [39]:
merged_df = merged_df.sort_values('Combined Row Number', ascending=True)
merged_df.head(5)
merged_df.columns
#new_df=merged_df[['Name','P/E_x','Row Number 1','ROIC  %','Row Number 2',	'Combined Row Number']]

Index(['S.No._x', 'Name', 'CMP  Rs._x', 'P/E_x', 'Mar Cap  Rs.Cr._x',
       'Div Yld  %_x', 'NP Qtr  Rs.Cr._x', 'Qtr Profit Var  %_x',
       'Sales Qtr  Rs.Cr._x', 'Qtr Sales Var  %_x', 'ROCE  %_x',
       'Row Number 1', 'S.No._y', 'CMP  Rs._y', 'P/E_y', 'Mar Cap  Rs.Cr._y',
       'Div Yld  %_y', 'NP Qtr  Rs.Cr._y', 'Qtr Profit Var  %_y',
       'Sales Qtr  Rs.Cr._y', 'Qtr Sales Var  %_y', 'ROCE  %_y', 'ROIC  %',
       'Row Number 2', 'Combined Row Number'],
      dtype='object')

In [21]:
excel_file_path = "data_extracted.xlsx"

# Save the DataFrame to an Excel file
new_df.to_excel(excel_file_path, index=False)